# Etapa de construcción
FROM node:16 as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# Etapa de pruebas
FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

CMD ["npm", "test"]
