export const ITEM_DELETED = "ITEM_DELETED";
export const ITEM_CREATED = "ITEM_CREATED";
export const ITEM_UPDATED = "ITEM_UPDATED";

export const USER_NAME_TAKEN = "USER_NAME_TAKEN";
export const EMAIL_TAKEN = "EMAIL_TAKEN";
export const NEED_VERIFIED_EMAIL = "NEED_VERIFIED_EMAIL";
export const ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
export const INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER";
export const INVALID_EMAIL = "INVALID_EMAIL";
export const INVALID_DATA = "INVALID_DATA";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";

export const BAD_REQUEST = "BAD_REQUEST";
export const SPECIAL_SIMBOLS = "SPECIAL_SIMBOLS";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const NOT_AUTHORIZED = "NOT_AUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";
export const WITHOUT_PERMISSIONS = "WITHOUT_PERMISSIONS";
export const NOT_FOUND = "NOT_FOUND";
export const REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
export const INTERNAL_ERROR = "INTERNAL_ERROR";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
export const BAD_GATEWAY = "BAD_GATEWAY";
export const GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT";
export const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const PLATFORM_TOKEN_ERROR = "PLATFORM_TOKEN_ERROR";
export const PLATFORM_ERROR = "PLATFORM_ERROR";

export const NOT_REMOVE_FILE = "NOT_REMOVE_FILE";
export const NOT_SEND_EMAIL = "NOT_SEND_EMAIL";
export const NOT_HAVE_DATA = "NOT_HAVE_DATA";
